version: "3.9"
   
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - DB_NAME_DEV=postgres
      - DB_USERNAME=postgres
      - DB_USER_PASSWORD=postgres
      - DB_HOST=127.0.0.1
      - DB_PORT=5432

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      ./.env
    environment:
      - DB_NAME_DEV=postgres
      - DB_USERNAME=postgres
      - DB_USER_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db