# Generated by Django 4.0 on 2022-01-18 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restful', '0003_alter_booking_updated_at_alter_booking_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_swimming_pools', to='restful.pool'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
