# Generated by Django 4.0 on 2022-01-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restful', '0004_alter_booking_pool_alter_booking_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='rating',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
