# Generated by Django 4.0 on 2022-01-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restful', '0005_remove_rating_updated_by_rating_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
